stages:
  load_data:
    cmd: python scripts/collect.py
    deps:
      - scripts/collect.py
      - pipeline/data_collector.py
    outs:
      - ${directories.data.raw}/${filenames.data.taxi}
      - ${directories.data.raw}/${filenames.data.zones}

  process_data:
    cmd: python scripts/process.py
    deps:
      - scripts/process.py
      - pipeline/data_processor.py
      - ${directories.data.raw}/${filenames.data.taxi}
      - ${directories.data.raw}/${filenames.data.zones}
    outs:
      - ${directories.data.processed}/${filenames.data.train}
      - ${directories.data.processed}/${filenames.data.validation}
      - ${directories.data.processed}/${filenames.data.test}

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - pipeline/model_trainer.py
      - ${directories.data.processed}/${filenames.data.train}
      - ${directories.data.processed}/${filenames.data.validation}
      - ${directories.data.processed}/${filenames.data.test}
    outs:
      - ${directories.model}/${filenames.model}
  
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - pipeline/model_evaluator.py
      - ${directories.model}/${filenames.model}
    outs:
      - data/reference/reference_data_2021-01.parquet
      
