directories:
  data:
    raw: data/raw
    processed: data/processed
  model: models
  report: reports

filenames:
  data:
    taxi: taxi-data.csv
    zones: taxi-zones.csv
    train: train.csv
    validation: validation.csv
    test: test
  model: xgb.json
  evaluation_report: eval_report.json

    